### PR TITLE
logic: Support matching closed issue with link

### PR DESCRIPTION
**Pull request by irgolic**
Note: I only tested this by hand in a python interpreter.

### CODE REVIEW

**Comment by samuelcolvin** [comment]
Thanks so much, we really need unit tests, but I guess adding this without is fine.

Also the idea is that this tool is not specific to pydantic (though it might never be used elsewhere), so I guess the org/user and repo should be `[^/+]` or similar?

**Comment by samuelcolvin** [comment]
And you can move the ID out of the regex group.

**Comment by irgolic** [comment]
> Also the idea is that this tool is not specific to pydantic (though it might never be used elsewhere), so I guess the org/user and repo should be `[^/+]` or similar?

Good idea. In that case, should we add org/user name and repo name to Settings? Alternatively I could match it to `[-a-zA-Z0-9]+` or something like [github username regex](https://github.com/shinnn/github-username-regex). That opens up a possibility for false positives though.

I'm matching `[-a-zA-Z0-9]+` for now.

Neat tool by the way!

**Comment by samuelcolvin** [comment]
Best to use `[^/]+` (sorry fixed above).

Can't add to settings since one deploy would serve all repos.

**Comment by irgolic** [comment]
> Best to use `[^/]+` (sorry fixed above).
> 
> Can't add to settings since one deploy would serve all repos.

Ah, that makes sense.

**Comment by samuelcolvin** [comment]
Thanks so much, will be auto deployed in a few minutes.

**Pull request merged**
